### ISSUE TITLE
Can’t understand what is the easy way to add custom headers in Fable.PowerPack.Fetch

### ISSUE THREAD

**Issue by ed-ilyin** [fable-compiler/fable-import#10]
Sorry for noob question: what is the easy way to add custom headers in Fable.PowerPack.Fetch?

**Comment by alfonsogarciacaro** [comment]
Here's an example, I hope it helps 😄 

```fsharp
  GlobalFetch.fetch(
    RequestInfo.Url url,
    requestProps
      [ RequestProperties.Method HttpMethod.POST
        requestHeaders [ContentType "application/json"]
        RequestProperties.Body !^(toJson myObject) ])
```

fable-powerpack contains helpers for most common cases [like this one](https://github.com/fable-compiler/fable-powerpack/blob/b035313b7376922446d51e503ef2913ef41d2172/src/Fetch.fs#L370-L380). You can also check [the tests](https://github.com/fable-compiler/fable-powerpack/blob/b035313b7376922446d51e503ef2913ef41d2172/tests/FetchTests.fs).
