### ISSUE TITLE
Pojo records vs union types

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fable-import#24]
Hi!

I'm working my way through various configuration types and while in the previous bindings I could use   

```f#
  [<KeyValueList>]
  type ApplicationOptions = 
    | BackgroundColor of int 
```

now, it seems that 
- either it has been changed to something else 
- or maybe it's the actual pixi JS implementation that has changed

So using a Pojo record works

```f#
  [<Pojo>]
  type ApplicationOptions = {
    backgroundColor: int
  }
```

while using a union type makes the compiler angry

```f#
  type ApplicationOptions = 
    | BackgroundColor of int 
```

So what should I use?
Thanks!

**Comment by MangelMaxime** [comment]
Yes we removed the `[<KeyValueList>]` attribute in Fable 1.x

You probably should not use record to manage your options because then you would need to set all the values of the records.

```fs
type ApplicationOptions  =
  { backgroundColor : int
    showCollision : bool }

// This is invalid because we miss the showCollision 
let myOpts =
  { backgroundColor  = 0 }
```

To use records, one solution could be:

```fs
[<Pojo>]
type ApplicationOptions  =
  { backgroundColor : int
    showCollision : bool }

  static member Default =
    { backgroundColor = 0
      showCollision= false }
      
let myOpts = { ApplicationOptions.Default with backgroundColor = 12 }
```

In general, I think most people use options like this:

```fs
open Fable.Core
open Fable.Core.JsInterop
open System

type OptionFromInterface =
 abstract backgroundColor: string option with get, set
 abstract showCollision: bool option with get, set
 
let opts1 = createEmpty<OptionFromInterface>
opts1.backgroundColor <- Some "red"
opts1.showCollision <- Some true

type OptionFromDU =
 | BackgroundColor of string
 | ShowCollision of bool
 
let opts = keyValueList CaseRules.None [ BackgroundColor "red"; ShowCollision true ]
```

[Check the code in the REPL](https://goo.gl/GHqqZY)

Using `OptionFromInterface` is easier because ts2fable generate this types for you from the `d.ts` files. When in order to use `OptionFromDU` you would need to edit the generated binding.

**Comment by whitetigle** [comment]
Thanks @MangelMaxime. 👍 

Now I really wonder what would be the easier to use from a JS dev point of view: Interface of discrimited union?

Which one should I enforce in my bindings?

**Comment by MangelMaxime** [comment]
Personally, I find `keyValueList` as a better option but it's return an `obj`. So we somehow loose type safety here, if we can't set it's type. One way, would be something like the next code, but it's doesn't feel right....

```fs
    type OptionFromInterface =
        abstract backgroundColor: string option with get, set
        abstract showCollision: bool option with get, set
     
    type OptionFromDU =
        | BackgroundColor of string
        | ShowCollision of bool
     
    type Application(?options: OptionFromInterface) =
        member __.options with get(): OptionFromInterface = jsNative and set(v: OptionFromInterface): unit = jsNative


    let inline createOptions<'T> (opts: OptionFromDU list) = keyValueList CaseRules.LowerFirst opts |> unbox<'T>

    let myOpts =
        createOptions<OptionFromInterface>
            [ BackgroundColor "red"
              ShowCollision true ]

    let app = Application(myOpts)

    //printfn "%A" myOpts.backgroundColor
    printfn "%A" app.options.backgroundColor
```

So, I think for now we are stuck with `OptionFromInterface`. But if you have an idea on how to use `keyValueList` and keeping the code type safe that would be awesome.

**Comment by whitetigle** [comment]
That's a good time to invoke @alfonsogarciacaro  :godmode:

**Comment by alfonsogarciacaro** [comment]
The interfaces are easier to generate automatically. I think the union types + `keyValueList` trick is more convenient when there are multiple options but it's difficult for the parser to know what's an option, so right now this is done manually :/

About interfaces, I haven't documented it yet, but based on feedback from FableConf where people didn't like `createEmpty` that much, latest Fable version (1.2.4) adds the `jsOptions` helper which can be used as follows:

```fsharp
open Fable.Core
open Fable.Core.JsInterop

type IOptions =
   abstract foo: string with get, set
   abstract bar: int with get, set

let opts = jsOptions<IOptions> (fun o ->
    o.foo <- "foo"
    o.bar <- 5
)
```

When possible this will be compiled directly as:

```js
var opts = { foo: "foo", bar: 5 }
```

**Comment by whitetigle** [comment]
Thanks!
Still I wonder about 

```f#
let opts = jsOptions<IOptions> (fun o ->
    o.foo <- "foo"
    o.bar <- 5
)
```

vs

```f#
let opts1 = createEmpty<IOptions>
opts1.backgroundColor <- Some "red"
opts1.showCollision <- Some true
```

Does JsOptions look more natural?

**Comment by MangelMaxime** [comment]
@whitetigle Please not that in your interface declaration you should option `string option`. 

I recommand this because, otherwise, we could have unexpected runtime errors because users would not have checked the properties before using it.

**Comment by whitetigle** [comment]
ok @MangelMaxime!

**Comment by alfonsogarciacaro** [comment]
@whitetigle In the FableConf workshops it seems some people didn't like the `createEmpty` thing very much. The other advantage of `jsOptions` (besides the name which makes the intention more explicit) is you can embed directly in the function call:

```fsharp
let createFoo(opts: IOptions) = importMember from "./foo.js"

// Note here you don't even need to type the generic arg
let foo = createFoo(jsOptions(fun o ->
    o.foo <- Some "foo"
    o.bar <- Some 5)
```

**Comment by whitetigle** [comment]
ok! I'll do that then. Should I prefix interfaces names with an Uppercase **I**?

**Comment by alfonsogarciacaro** [comment]
It's a .NET convention but not really necessary, you just use the same names as in Pixi .d.ts file :)

**Comment by whitetigle** [comment]
ok 👍
