### ISSUE TITLE
ValidityState missing tooShort

### ISSUE THREAD

**Issue by desjardinsm** [fable-compiler/fable-import#25]
Apologies if this is just me being dense, but as far as I can tell `ValidityState.tooShort` [does not exist](https://github.com/fable-compiler/fable-import/blob/master/Browser/Fable.Import.Browser.fs#L8558) where it should.

([MDN ValidityState for reference](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState))

**Comment by alfonsogarciacaro** [comment]
Hi @desjardinsm, no apologies needed at all! There may be indeed some errors in the bindings, thanks a lot for the catch! If this property does exist in `ValidityState` could you please send a PR to add it?

Thanks again for your help!
