### ISSUE TITLE
Pixi bindings

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fable-import#27]
Hi!
I'm in the process of releasing the first version of bindings for Pixi.js in fable-import.

But before I do so, I have a question: I also have bindings for **pixi particles** and **pixi-sound** which are kind of optional child libraries yet important ones. I use all of them in samples-pixi

So shall I put them in the same pixi folder?

**Comment by MangelMaxime** [comment]
I think we should seperate them and have one package per lib

**Comment by alfonsogarciacaro** [comment]
Yes, if they require extra JS dependencies maybe it's better to have a separate package so it's more evident for the user they need to install extra JS dependencies together with the extra bindings (also in the hope Paket will be able to manage npm dependencies in the future).

**Comment by whitetigle** [comment]
Well they don't need any extra dependencies since they rely on either pixi or pure browser api. 
So what do I do? 😉

**Comment by alfonsogarciacaro** [comment]
Ah! In that case, maybe they can be put in the same packages. If `Fable.Import.Pixi` is a pure binding (it doesn't contain actual code) it can be distributed a .dll so including the extra bindings shouldn't pose too much overhead 😄

**Comment by whitetigle** [comment]
ok 👍 @MangelMaxime is it ok for you too?

**Comment by MangelMaxime** [comment]
As long as the bindings have the same dependency (only pixi.js) it's make sense to create only one binding with all of them under different module/namespace.

So yes, I am ok :)

**Comment by whitetigle** [comment]
ok!
