### ISSUE TITLE
Update AnimeJS bindings

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-import#29]
According to the documentation of animejs: https://github.com/juliangarnier/anime

We can use `import anime from animejs` to include the lib in our project. To take advantage fo treeshaking and also use webpack include the dependency we need to update the binding to import `import` statements

**Comment by whitetigle** [comment]
ok. I'm not a real specialist in the matter but I'll try to fix that. Thanks for reporting @MangelMaxime 👍
