### ISSUE TITLE
Clean Pixi binding

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-import#31]
In Pixi binding it's seems there is still reference for:

- [particules](https://github.com/fable-compiler/fable-import/blob/master/Pixi/Fable.Import.Pixi.fs#L2090-L2151)

@whitetigle Do you confirm, it's the same as for pixi-particules binding ?

**Comment by whitetigle** [comment]
No it's not the same thing at all. I haven't thought of that. 

This is some specialized particle container designed to render same kind of sprites faster while pixi-particles is a system to animate sprites. But I think pixi-particles uses the particle container for its emitters.

So what do we do?

**Comment by MangelMaxime** [comment]
Ah so the listed code is coming from PIXI ? If so we should be good to go like that.
