### ISSUE TITLE
Fable.Import.Node 0.2.0 not working

### ISSUE THREAD

**Issue by jgrund** [fable-compiler/fable-import#33]
Upon installing 0.2.0 of `Fable.Import.Node`, I am seeing:

```
    /home/travis/build/jgrund/fable-jest/test/Matchers.test.fs(106,24): (106,28) error FSHARP: The value, constructor, namespace or type 'Node' is not defined.

,/home/travis/build/jgrund/fable-jest/test/Matchers.test.fs(109,13): (109,17) error FSHARP: The namespace or module 'Node' is not defined.,/home/travis/build/jgrund/fable-jest/test/Matchers.test.fs(109,4): (109,36) error FSHARP: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
```

Ex: https://travis-ci.org/jgrund/fable-jest

**Comment by jgrund** [comment]
Looking at the packages, 0.2.0 is much smaller than 0.1.5:

<img width="427" alt="screen shot 2017-12-16 at 8 35 28 am" src="https://user-images.githubusercontent.com/458717/34070947-3ac9bd18-e23c-11e7-8a6b-9fd027b6f556.png">

**Comment by jgrund** [comment]
Building locally yields a similar file size. 

<img width="494" alt="screen shot 2017-12-16 at 8 43 05 am" src="https://user-images.githubusercontent.com/458717/34070998-2a30b7a8-e23d-11e7-98dd-d7a88c7f40b8.png">

Not sure why the uploaded one is much smaller.

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @jgrund! Hmm, it seems Paket push is causing problem, I changed the build script so `dotnet pack/push` is used instead. Can you please try with Fable.Import.Node 0.2.1? Sorry for the trouble!

**Comment by forki** [comment]
Paket push is causing problem? How?

Am 16.12.2017 17:45 schrieb "Alfonso Garcia-Caro" <notifications@github.com

**Comment by alfonsogarciacaro** [comment]
According to @jgrund report, the version published using Paket.push [in this commit](https://github.com/fable-compiler/fable-import/commit/81b0a7838922bfab6c8bd8b38c0b0b89c7ad8b46) is not working. I had similar problems in other repos but didn't investigate too much because using `dotnet pack/push` just fixes the issue.

**Comment by jgrund** [comment]
Looks like 0.2.1 is working.

**Comment by forki** [comment]
> version published using Paket.push in this commit is not working

how? it's just pushing the nupkg - how can there possibly be any difference?

**Comment by alfonsogarciacaro** [comment]
It's a mystery for me too, sorry. If it helps [this is the commit](https://github.com/fable-compiler/fable-import/commit/81b0a7838922bfab6c8bd8b38c0b0b89c7ad8b46) right before removing `Paket.Push`.
