### ISSUE TITLE
AutoOpen of let binding imports problematic

### ISSUE THREAD

**Issue by jgrund** [fable-compiler/fable-import#41]
In the Nodejs bindings, we currently `AutoOpen` `Exports` inside which we have a bunch of let bound imports.

This is problematic as it is no longer possible to cleanly overload parts of a module since the module is now scoped as a let binding.

It seems like the ideal solution is to rename the let bound export (creating a variant between import and types).

This way it will still be possible to overload parts of a module.

**Comment by jgrund** [comment]
Thinking of making the export names lowercase as was done in the ts2fable node bindings by @ctaggart

**Comment by alfonsogarciacaro** [comment]
This may work, it agrees with the convention that let bindings are lower case in F# :+1:
