### ISSUE TITLE
variable types in bindings for port should be int not float

### ISSUE THREAD

**Issue by tanabarr** [fable-compiler/fable-import#45]
In https://github.com/fable-compiler/fable-import/blob/master/Node/Https.fs https://github.com/fable-compiler/fable-import/blob/master/Node/Http.fs and https://github.com/fable-compiler/fable-import/blob/master/Node/Net.fs "port" variables should be of type _int_ rather than _float_. 
If someone could confirm that this is correct I can do a PR.

**Comment by jgrund** [comment]
Sounds good to me 😄

**Comment by MangelMaxime** [comment]
Indeed we can set it to `int` as this is not generated via ts2fable.

**Comment by jgrund** [comment]
@tanabarr If you are able to add a few tests for this that would be great, if not no worries.
