### ISSUE TITLE
Publlish new Fable.Import.Browser

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-import#52]
@alfonsogarciacaro Could we publish the new Fable.Import.Browser as 1.3.0 or 2.0 as it's improved a lit the API. Especially with for the `addEventListener` :)

**Comment by alfonsogarciacaro** [comment]
Sorry for the delay, I just published it! The previous version was 0.1.2 so I guess it was time to release it as 1.0.0 ;)

**Comment by MangelMaxime** [comment]
Ah yes sorry :)

I read 1.2.0 :D thanks if more for new users :)
