### ISSUE TITLE
Cannot resolve Fable.Import.Browser.Intl.NumberFormat in Fable2

### ISSUE THREAD

**Issue by AkosLukacs** [fable-compiler/fable-import#72]
I think there is a breaking change in Fable2. This code fails to compile:
```fsharp
let nf = Fable.Import.Browser.Intl.NumberFormat.Create("en-us")
let formatted = nf.format(123456789.01)
printfn "formatted: %A" formatted
```
`FABLE: Cannot resolve Fable.Import.Browser.Intl.NumberFormat` at the first line.

Fails both in the [REPL](https://fable.io/repl/#?code=DYUwLgBAdgZhC8EBiBDARqAdASQLYAcB7AJzEwCFjCB3AZxGJyjGEwDkBXXNBpE3FGQDCxEIJAAKAEQgoAWg60pASgBQoSDH6CwIACYJoMTFuICwEgIwAmAMwAWAKwA2AOwAOAJyYADJbX4xACWzDBQEFKm5rp6AFwQAKQAglIQUTr6QA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA), and in my project. But intellisense and tooltips do work both in the Repl and in VS Code:

![in repl](https://files.gitter.im/fable-compiler/Fable/rwaI/image.png)

Tried to create a failing test case, and looks like this code compiles and works in Fable 1.x. After updating to Fable 2, it is not 100% consistent, at least couldn't find docs how to test the imports, so just started hacking in the test folder...

**Comment by alfonsogarciacaro** [comment]
Ups, you're right. This is a regression from Fable 1. [It will be fixed in Fable 2.1](https://github.com/fable-compiler/Fable/commit/518cc61f0222cf3ecfabcbc59ac70ddd67b60520), to be announced shortly. Thanks for reporting!

**Comment by AkosLukacs** [comment]
A related issue, looking at the commit, probably already fixed, but now the custom name of a `[<Global>]` module is ignored:

```fsharp
open Fable.Core

[<Global("console")>]
module JustAnExample = 
    let log: string -> unit = jsNative
    let log2(msg: string): unit = jsNative

JustAnExample.log("hi")
JustAnExample.log2("hi")
```
Gets compiled to `JustAnExample$$$log("hi")`. I would expect `console.log("hi")`. 

[Repl link](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChcDaAPAOJLAJxIAUARAMbAQDOwKtAlAHwC6uAtsAAmAVxRQAUiOYAXAIIQAogA84-EOIC8UXFD1QUMg8ADmALiiysASwgmoAWi5QREa0e0ArZgDk4M6wA3PH0DMCNyExNqfmZzSxkbOw4LV3coL19-ILxcKVkFFTUNNEi6AAtrTjzpeSVVdRRUSOjaSs4gA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

**Comment by alfonsogarciacaro** [comment]
Yes, it should be fixed :) Can you please upload fable-loader (check the new [usage instructions](https://www.npmjs.com/package/fable-loader#installation)) and see it it works?

**Comment by AkosLukacs** [comment]
It's working now, thank you!
