### ISSUE TITLE
Guide to Reading the .fs file

### ISSUE THREAD

**Issue by shubhamkumar13** [fable-compiler/fable-import#77]
Is there a way to read  Fable.Import.Pixi.fs file? I cannot identify functions which can be used.

Sorry if it's a noob question but I want to use Pixi.js in fsharp.

**Comment by MangelMaxime** [comment]
When creating the bindings @whitetigle ported all the Pixi examples. You can find them [here](https://github.com/fable-compiler/samples-pixi).

I guess [this guide](https://medium.com/@zaid.naom/f-interop-with-javascript-in-fable-the-complete-guide-ccc5b896a59f) and the [Fable interop](https://fable.io/docs/interacting.html) documentation can also help you.

**Comment by shubhamkumar13** [comment]
Is it bad if I didn't get how to use it, even after reading those

**Comment by MangelMaxime** [comment]
Hum, what is missing in the examples?

**Comment by MangelMaxime** [comment]
Ok :)

Feel free to ask questions here or the [Gitter](https://gitter.im/fable-compiler/Fable) or the [F# slack](https://fsharp.org/guides/slack/).

**Comment by whitetigle** [comment]
@shubhamkumar13 sorry for the delay. Please feel free to ping me if needed. 
Please note that I have not yet updated the bindings for Fable 2 though.
