### ISSUE TITLE
missing types MediaStreamConstraints, NavigatorUserMediaSuccessCallback, NavigatorUserMediaErrorCallback

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/fable-import#79]
references https://github.com/fable-compiler/ts2fable/issues/290

--------------

babylonjs contains this:

```ts
interface Navigator {
    mozGetVRDevices: (any: any) => any;
    webkitGetUserMedia(constraints: MediaStreamConstraints, successCallback: NavigatorUserMediaSuccessCallback, errorCallback: NavigatorUserMediaErrorCallback): void;
    mozGetUserMedia(constraints: MediaStreamConstraints, successCallback: NavigatorUserMediaSuccessCallback, errorCallback: NavigatorUserMediaErrorCallback): void;
    msGetUserMedia(constraints: MediaStreamConstraints, successCallback: NavigatorUserMediaSuccessCallback, errorCallback: NavigatorUserMediaErrorCallback): void;
    webkitGetGamepads(): Gamepad[];
    msGetGamepads(): Gamepad[];
    webkitGamepads(): Gamepad[];
}
```

That causes an error:

![grafik](https://user-images.githubusercontent.com/4236651/53042030-aa104b00-3485-11e9-9f16-2958c2f6b2e9.png)

If I F12 on ``MediaStreamConstraints`` in Visual Studio in the babylon.d.ts file, I go to ``C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.8\lib.dom.d.ts``.

So I think these types need to be added to ``Fable.Import.Browser``.

**Comment by alfonsogarciacaro** [comment]
Sorry for the hassle, but the plan is not to update this package anymore and instead break everything into smaller packages for easier maintenance, so https://github.com/fable-compiler/fable-browser/issues/2 was actually the good one 😅 

Following the spirit of the [new approach](https://github.com/fable-compiler/fable-browser/issues/1), could you please create a new package for compatibility with the [Media Stream API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API)? You can PR that package to fable-browser or keep it in your GH profile if you prefer :+1:

**Comment by 0x53A** [comment]
Okay thanks!

I wont' be able to get to it the next month or two, busy finishing the current project.

Since I don't actually need the media stuff, I just need babylonjs to compile, I dropped this file into my project:

```f#
namespace Fable.Import.Browser

type [<AllowNullLiteral>] MediaStreamConstraints = interface end
type [<AllowNullLiteral>] NavigatorUserMediaSuccessCallback = interface end
type [<AllowNullLiteral>] NavigatorUserMediaErrorCallback = interface end
```
