### ISSUE TITLE
Add navigator.languages to Fable.Import.Browser

### ISSUE THREAD

**Issue by nelson831002** [fable-compiler/fable-import#83]
It is still an [experimental property](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages) but wondering if there are plans to include it

**Comment by MangelMaxime** [comment]
Hello, 
it seems like most browsers has it implemented even if experimental.

I think we can indeed add it to the binding, would like to send a PR?

**Comment by nelson831002** [comment]
Hi Maxime
Sure thing, here it is: [84](https://github.com/fable-compiler/fable-import/pull/84)

**Comment by MangelMaxime** [comment]
Thank you, 
your PR is included in version 1.4.0 of Fable.Import.Browser
