### ISSUE TITLE
Cannot find replacement for Fable.Import.express.Globals::static

### ISSUE THREAD

**Issue by ed-ilyin** [fable-compiler/fable-import#9]
I'm not sure which of two Fable.Import.Express reps is right place to post this issue.
This is same issue as https://github.com/fable-compiler/fable-express/issues/5

this two lines of code gives compile time error:
```
open Fable.Import
let s = express.``static``
```
`error FABLE: Cannot find replacement for Fable.Import.express.Globals::static`

**Comment by alfonsogarciacaro** [comment]
Thanks for the report @ed-ilyin! I've released Fable 1.1.4 to fix this, could you please update and try again? Remember you need to update both Fable.Core in paket.dependencies (then run `.paket/paket.exe install`) and dotnet-fable in the .fsproj file (then run `dotnet restore`, if necessary, use `dotnet restore --no-cache`). Cheers!

**Comment by ed-ilyin** [comment]
Thank you @alfonsogarciacaro . Indeed fixes.
